### ISSUE TITLE
Translate menu items in footer 

### ISSUE THREAD

**Issue by spapastamkou** [C2DH/ranketwo#218]
I want to translate the items of the menu of the footer in FR and DE pages that now appear mixed with EN. I checked the files of the `/_data/` folder and I wonder if this has to be done from `navigation.yaml` or `i18n.yaml` ? Could you guide me a bit please @frederic-reis @danieleguido ? Thanks! 

![menu-in-footer](https://user-images.githubusercontent.com/27706167/220163787-a9f1e4aa-c4b5-4fff-901b-d237156e994f.png)

**Comment by frederic-reis** [comment]
### For links

You have to add entries in the _data/i18n.yaml file

Example:
```
Who we are:
  en: Who we are
  fr: Qui somme-nous
  de: ...
```

But the link texts are hard-coded for the moment in the `_includes/footer.html` file. You have to replace them with the code to include translation.

Example:
Replace` Who we are` by `{% assign key="Who we are"%}{% include t.html %}`

**Comment by frederic-reis** [comment]
It's the same for the footer text. You have to include the translation mechanism.

By example, you can replace the text by {% assign key="footer.text1"%}{% include t.html %}

And add in the _data/i18n.yaml file:
```
footer.text1:
  en: A project initiated by <a href="https://www.c2dh.uni.lu/people/andreas-fickers" target='_blank'>Andreas Fickers</a> &mdash; Concept & coordination by <a href="https://www.c2dh.uni.lu/people/stefania-scagliola" target='_blank'>Stefania Scagliola</a>
  fr: ...
  de: ...
```
